/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class ListSetor extends javax.swing.JFrame {

    /** Creates new form listSetor */
    public ListSetor() {
        initComponents();
        carregarLista();
    }
    
    public void carregarLista(){
        DefaultTableModel modelo = (DefaultTableModel) tblSetor.getModel();
        modelo.setNumRows(0);
        DAO.DaoSetor itensSetor = new DAO.DaoSetor();
        ResultSet dados = itensSetor.listar();
        
        try{
            while(dados.next()){
                modelo.addRow(new Object[]{
                    dados.getString(1),
                    dados.getString(2),
                    dados.getString(3)
                
                });
            }
        }catch(SQLException error){
            throw new RuntimeException(error);
        }
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSetor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAlterar8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSetor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Setor", "Codigo da Categoria"
            }
        ));
        jScrollPane1.setViewportView(tblSetor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 82, 520, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("LISTAGEM DE SETORES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 327, 38));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/criss-cross.png"))); // NOI18N
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 130, 100));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VOLTAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 130, 30));

        btnAlterar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/change.png"))); // NOI18N
        btnAlterar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 130, 100));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DELETAR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 130, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/update.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 130, 90));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ATUALIZAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/online-store-1674907_1280.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

        if(tblSetor.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
        }else{
            int linha = tblSetor.getSelectedRow();
            int id = Integer.parseInt((String)  tblSetor.getValueAt(linha, 0));
            DAO.DaoSetor excluirFuncionario = new DAO.DaoSetor();
            excluirFuncionario.excluir(id);

            carregarLista();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar8ActionPerformed
        // TODO add your handling code here:
        if(tblSetor.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");

        }else{
            String codigo, nome, categoria;
            int linha = tblSetor.getSelectedRow();
            codigo = (String) tblSetor.getValueAt(linha,0);
            nome = (String) tblSetor.getValueAt(linha, 1 );
            categoria = (String) tblSetor.getValueAt(linha, 2 );
            
            Alterar_setor alSetor = new Alterar_setor();
            alSetor.resgatar(codigo, nome, categoria);
            alSetor.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnAlterar8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ListMenu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar8;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSetor;
    // End of variables declaration//GEN-END:variables

}
